image: docker:stable
variables:
    PROJECT: "nlp"
    KEYS_DEV: "-p 127.0.0.1:9035:5000"
    KEYS_PROD: "-p 127.0.0.1:9035:5000"

include: 
  - project: 'root/template-gitlab'
    ref: master
    file: '/template-gitlab-ci.yml'
